require:
  - rubocop-packaging
  - rubocop-performance

inherit_from: .rubocop_todo.yml

AllCops:
  DisplayCopNames: true
  NewCops: enable
  SuggestExtensions: false

Bundler/DuplicatedGem:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
    - '*.gemspec'

Metrics/ModuleLength:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Style/IfUnlessModifier:
  Exclude:
    - 'Gemfile'

Style/NumericLiterals:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/RedundantPercentQ:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/FetchEnvVar:
  Enabled: false

Naming/VariableNumber:
  Exclude:
    - 'spec/backlog_kit/client_spec.rb'
    - 'spec/backlog_kit/hash_extensions_spec.rb'

Gemspec/RequireMFA:
  Enabled: false
